name: colinsummers
favicon: null
layout_spectrum: 0.736616189358756
typography_spectrum: 0.9968227348290384
title: Colin Summers
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#feb914'
    - '#070707'
    - '#4b6eae'
    - '#f8faec'
    - '#a6742b'
  brandStrength: 0.625
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
